package view;

public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuNovoProduto = new javax.swing.JMenuItem();
        jMenuGerenciarProduto = new javax.swing.JMenuItem();
        jMenuMovimentarEstoque = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuListarProecos = new javax.swing.JMenuItem();
        jMenuBalancoFinanceiro = new javax.swing.JMenuItem();
        jMenuProdutosPorCategoria = new javax.swing.JMenuItem();
        jMenuAbaixoDaMinima = new javax.swing.JMenuItem();
        jMenuAcimaDaMaxima = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Arquivo");

        jMenuSobre.setText("Sobre");
        jMenu1.add(jMenuSobre);

        jMenuSair.setText("Sair");
        jMenu1.add(jMenuSair);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Controle");

        jMenuNovoProduto.setText("Cadastro produto");
        jMenu4.add(jMenuNovoProduto);

        jMenuGerenciarProduto.setText("Gerencia produto");
        jMenuGerenciarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerenciarProdutoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuGerenciarProduto);

        jMenuMovimentarEstoque.setText("Movimentação");
        jMenuMovimentarEstoque.setToolTipText("");
        jMenu4.add(jMenuMovimentarEstoque);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Relatórios");

        jMenuListarProecos.setText("Lista de preços");
        jMenuListarProecos.setToolTipText("");
        jMenuListarProecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarProecosActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuListarProecos);

        jMenuBalancoFinanceiro.setText("Balanço financeiro");
        jMenu5.add(jMenuBalancoFinanceiro);

        jMenuProdutosPorCategoria.setText("Produto por categoria");
        jMenu5.add(jMenuProdutosPorCategoria);

        jMenuAbaixoDaMinima.setText("Produtos abaixo da quantidade mínima");
        jMenu5.add(jMenuAbaixoDaMinima);

        jMenuAcimaDaMaxima.setText("Produtos acima da quantidade máxima");
        jMenuAcimaDaMaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAcimaDaMaximaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuAcimaDaMaxima);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuGerenciarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerenciarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuGerenciarProdutoActionPerformed

    private void jMenuAcimaDaMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAcimaDaMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAcimaDaMaximaActionPerformed

    private void jMenuListarProecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListarProecosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuListarProecosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAbaixoDaMinima;
    private javax.swing.JMenuItem jMenuAcimaDaMaxima;
    private javax.swing.JMenuItem jMenuBalancoFinanceiro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuGerenciarProduto;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuListarProecos;
    private javax.swing.JMenuItem jMenuMovimentarEstoque;
    private javax.swing.JMenuItem jMenuNovoProduto;
    private javax.swing.JMenuItem jMenuProdutosPorCategoria;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenuItem jMenuSobre;
    // End of variables declaration//GEN-END:variables
}
