package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Categoria;
import model.Produto;

public class FrmProdutoNovo extends javax.swing.JFrame {

    public List<Produto> produtos = new ArrayList();

    /**
     * Creates new form JProdutoNovo
     */
    public FrmProdutoNovo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JBAdicionarProduto = new javax.swing.JButton();
        JBVoltar = new javax.swing.JButton();
        JTFValorProduto = new javax.swing.JTextField();
        JTFIdProduto = new javax.swing.JTextField();
        JTFUniProduto = new javax.swing.JTextField();
        JTFQuantidadeMinimaProduto = new javax.swing.JTextField();
        JTFQuantidadeMaximaProduto = new javax.swing.JTextField();
        JTFQuantidadeProduto = new javax.swing.JTextField();
        JTFNomeProduto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JTFCategoria = new javax.swing.JTextField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Novo Produto");

        jLabel2.setText("Nome:");

        jLabel4.setText("ID:");

        jLabel5.setText("Valor Unitário:");

        jLabel6.setText("Quantidade máxima em estoque:");

        jLabel7.setText("Unidade:");

        jLabel8.setText("Quantidade em estoque:");

        jLabel9.setText("Quantidade mínima em estoque:");

        JBAdicionarProduto.setText("Adicionar novo produto");
        JBAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAdicionarProdutoActionPerformed(evt);
            }
        });

        JBVoltar.setText("Voltar");
        JBVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBVoltarMouseClicked(evt);
            }
        });
        JBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBVoltarActionPerformed(evt);
            }
        });

        JTFValorProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFValorProdutoActionPerformed(evt);
            }
        });

        JTFIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFIdProdutoActionPerformed(evt);
            }
        });

        JTFUniProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFUniProdutoActionPerformed(evt);
            }
        });

        JTFQuantidadeMinimaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFQuantidadeMinimaProdutoActionPerformed(evt);
            }
        });

        JTFQuantidadeMaximaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFQuantidadeMaximaProdutoActionPerformed(evt);
            }
        });

        JTFQuantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFQuantidadeProdutoActionPerformed(evt);
            }
        });

        JTFNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNomeProdutoActionPerformed(evt);
            }
        });

        jLabel11.setText("Categoria:");

        JTFCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFNomeProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFIdProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFValorProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFUniProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFQuantidadeProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFQuantidadeMinimaProduto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFQuantidadeMaximaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JTFCategoria)))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBVoltar)
                .addGap(186, 186, 186)
                .addComponent(JBAdicionarProduto)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTFValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JTFUniProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JTFQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(JTFQuantidadeMinimaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTFQuantidadeMaximaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBAdicionarProduto)
                    .addComponent(JBVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_JBVoltarMouseClicked

    private void JTFNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNomeProdutoActionPerformed

    }//GEN-LAST:event_JTFNomeProdutoActionPerformed

    private void JTFIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFIdProdutoActionPerformed

    }//GEN-LAST:event_JTFIdProdutoActionPerformed

    private void JTFValorProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFValorProdutoActionPerformed

    }//GEN-LAST:event_JTFValorProdutoActionPerformed

    private void JTFUniProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFUniProdutoActionPerformed
    }//GEN-LAST:event_JTFUniProdutoActionPerformed

    private void JTFQuantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFQuantidadeProdutoActionPerformed
     }//GEN-LAST:event_JTFQuantidadeProdutoActionPerformed

    private void JTFQuantidadeMinimaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFQuantidadeMinimaProdutoActionPerformed

    }//GEN-LAST:event_JTFQuantidadeMinimaProdutoActionPerformed

    private void JTFQuantidadeMaximaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFQuantidadeMaximaProdutoActionPerformed

    }//GEN-LAST:event_JTFQuantidadeMaximaProdutoActionPerformed

    private void JTFCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCategoriaActionPerformed

    }//GEN-LAST:event_JTFCategoriaActionPerformed

    private void JBAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAdicionarProdutoActionPerformed

        try {
            String nome = "";
            int id = 0;
            int valorUnitario = 0;
            String unidade = "";
            int quantidadeEstoque = 0;
            int quantidadeEstoqueMinima = 0;
            int quantidadeEstoqueMaxima = 0;
            String nomeCategoria = "";

            //Nome do Produto
            if (this.JTFNomeProduto.getText().length() < 2) {
                throw new Mensagem(" O nome do produto deve conter ao menos 2 caracteres. ");
            } else {
                nome = this.JTFNomeProduto.getText();
            }

            //Id do Produto
            int x = Integer.parseInt(this.JTFIdProduto.getText());
            if (x <= 0) {
                throw new Mensagem("O Id do produto deve ser número e maior que zero. ");
            }
            if (this.JTFIdProduto.getText().length() <= 0) {
                throw new Mensagem("O Id do produto deve ser número e maior que zero. ");
            } else {
                id = Integer.parseInt(this.JTFIdProduto.getText());
            }

            //Valor do produto
            x = Integer.parseInt(this.JTFValorProduto.getText());
            if (x <= 0) {
                throw new Mensagem("O Id do produto deve ser número e maior que zero. ");
            }
            if (this.JTFValorProduto.getText().length() <= 0) {
                throw new Mensagem("O valor do produto deve ser número e maior que zero. ");
            } else {
                valorUnitario = Integer.parseInt(this.JTFValorProduto.getText());
            }

            //Unidade de medida do Produto
            if (this.JTFUniProduto.getText().length() < 2) {
                throw new Mensagem("A unidade de medida tem que ser válida e conter ao menos 2 caracteres. ");
            } else {
                unidade = this.JTFUniProduto.getText();
            }

            //Quantidade do produto
            x = Integer.parseInt(this.JTFQuantidadeProduto.getText());
            if (x <= 0) {
                throw new Mensagem("O Id do produto deve ser número e maior que zero. ");
            }
            if (this.JTFQuantidadeProduto.getText().length() <= 0) {
                throw new Mensagem("Insira uma quantidade válida. ");
            } else {
                quantidadeEstoque = Integer.parseInt(this.JTFQuantidadeProduto.getText());
            }

            //Quantidade Mínima do produto
            x = Integer.parseInt(this.JTFQuantidadeMinimaProduto.getText());
            if (x <= 0) {
                throw new Mensagem("O Id do produto deve ser número e maior que zero. ");
            }
            if (this.JTFQuantidadeMinimaProduto.getText().length() <= 0) {
                throw new Mensagem("A quantidade mínima do produto deve ser número e maior que zero. ");
            } else {
                id = Integer.parseInt(this.JTFQuantidadeMinimaProduto.getText());
            }

            //Quantidade Máxima do produto
            x = Integer.parseInt(this.JTFQuantidadeMaximaProduto.getText());
            if (x <= 0) {
                throw new Mensagem("O Id do produto deve ser número e maior que zero. ");
            }
            if (this.JTFQuantidadeMaximaProduto.getText().length() <= 0) {
                throw new Mensagem("A quantidade máxima do produto deve ser número e maior que zero. ");
            } else {
                id = Integer.parseInt(this.JTFQuantidadeMaximaProduto.getText());
            }

            //Categoria do Produto
            if (this.JTFCategoria.getText().length() <= 0) {
                throw new Mensagem("Insira um nome de categoria válido. ");
            } else {
                nomeCategoria = JTFCategoria.getText();
            }

            // limpa campos da interface
            this.JTFNomeProduto.setText("");
            this.JTFIdProduto.setText("");
            this.JTFValorProduto.setText("");
            this.JTFUniProduto.setText("");
            this.JTFQuantidadeProduto.setText("");
            this.JTFQuantidadeMinimaProduto.setText("");
            this.JTFQuantidadeMaximaProduto.setText("");
            this.JTFCategoria.setText("");

            Produto produto = new Produto(nome, id, valorUnitario, unidade, quantidadeEstoque, quantidadeEstoqueMinima, quantidadeEstoqueMaxima, nomeCategoria);
            produtos.add(produto);

            JOptionPane.showMessageDialog(this, "Produto adicionado com sucesso!");

        } catch (Mensagem e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro ao converter número: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage());
        }


    }//GEN-LAST:event_JBAdicionarProdutoActionPerformed

    private void JBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBVoltarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAdicionarProduto;
    private javax.swing.JButton JBVoltar;
    private javax.swing.JTextField JTFCategoria;
    private javax.swing.JTextField JTFIdProduto;
    private javax.swing.JTextField JTFNomeProduto;
    private javax.swing.JTextField JTFQuantidadeMaximaProduto;
    private javax.swing.JTextField JTFQuantidadeMinimaProduto;
    private javax.swing.JTextField JTFQuantidadeProduto;
    private javax.swing.JTextField JTFUniProduto;
    private javax.swing.JTextField JTFValorProduto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
